spring:
  cache:
    type: redis
  redis:
    host: 14.103.149.91
    port: 6379
    password: wakeyoga123
    database: 15
  # 数据库相关配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 2cbef9494050eb99
      url: jdbc:mysql://14.103.149.91:3306/pigxx_boot?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true

cnipr:
  user-account: "zhonggao_gaotu"
  user-password: "ZhongGao1314@"
  client-id: "F06C930529889BAC8978C141106C158D"
  client-secret: "6635D2B036D3A7E0B55137851DC71138"
