## spring security 配置
security:
  oauth2:
    client:
      ignore-urls:
        - /**
spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: wakeyoga123
      database: 15
  # 数据库相关配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 2cbef9494050eb99
      url: jdbc:mysql://127.0.0.1:3306/pigxx_boot?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
rocketmq:
  name-server: 14.103.181.209:9876
  producer:
    group: my-producer-group
    send-message-timeout: 10000 # 默认3000ms，改成10秒
    retry-times-when-send-failed: 3 # 失败重试次数
    retry-next-server: true # 失败切换broker

cnipr:
  user-account: "zhonggao_gaotu"
  user-password: "ZhongGao1314@"
  client-id: "F06C930529889BAC8978C141106C158D"
  client-secret: "6635D2B036D3A7E0B55137851DC71138"
