## spring security 配置
security:
  oauth2:
    client:
      ignore-urls:
        - /**
spring:
  cache:
    type: redis
  data:
    redis:
      host: 47.100.8.163
      port: 6379
      password: Sq^7XikvSiDvKlUi
      database: 15
  # 数据库相关配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: End_master
      password: End_master
      url: jdbc:mysql://mysql-e2e14a41c6a0-public.rds.volces.com:3306/pigxx_boot?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
rocketmq:
  producer:
    endpoints: rmq-cn-pe336a2zb0u.cn-shanghai.rmq.aliyuncs.com:8080
    namespace: rmq-cn-pe336a2zb0u
    accessKey: 00l26kQG3DZ6e4Li
    secretKey: 7CsbvhYD206ga5QB

cnipr:
  user-account: "zhonggao_gaotu"
  user-password: "ZhongGao1314@"
  client-id: "F06C930529889BAC8978C141106C158D"
  client-secret: "6635D2B036D3A7E0B55137851DC71138"

