## spring security é…ç½®
security:
  oauth2:
    client:
      ignore-urls:
        - /**
spring:
  cache:
    type: redis
  data:
    redis:
      host: 14.103.193.249
      port: 6379
      password: wakeyoga123
      database: 1
  # æ•°æ®åº“ç›¸å…³é…ç½®
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: c45540d049692a9c
      url: jdbc:mysql://14.103.193.249:3306/kyd?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
  elasticsearch:
    uris: 14.103.193.249:9200
    username: elastic
    password: COwkX393BF

easy-es:
  address: ${spring.elasticsearch.uris}
  username: ${spring.elasticsearch.username}
  password: ${spring.elasticsearch.password}

rocketmq:
  name-server: 14.103.193.249:9876
  producer:
    group: my-producer-group
    send-message-timeout: 10000 # é»˜è®¤3000msï¼Œæ”¹æˆ10ç§’
    retry-times-when-send-failed: 3 # å¤±è´¥é‡è¯•æ¬¡æ•°
    retry-next-server: true # å¤±è´¥åˆ‡æ¢broker

# =========================
# ğŸ“¦ ä¸­ç§‘é™¢ä¸“åˆ©æ¥å£é…ç½®
# =========================
yt:
  base-url: http://14.103.193.249:9898/admin/cnipr
  sf1-v1-url: ${yt.base-url}/page
  pi11-url:  ${yt.base-url}/pdfUrl
  pi12-url:  ${yt.base-url}/absUrl
  pi16-url:  ${yt.base-url}/imgUrl

# =========================
# ğŸ· PigX é…ç½®
# =========================
pigx:
  mybatis:
    show-sql: false