# =========================
# ğŸŒ Spring Security é…ç½®
# =========================
security:
  oauth2:
    client:
      ignore-urls:
        - /**

# =========================
# ğŸ§  ç¼“å­˜ Redis é…ç½®
# =========================
spring:
  cache:
    type: redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: wakeyoga123
      database: 1

  # =========================
  # ğŸ—„ï¸ æ•°æ®åº“é…ç½®ï¼ˆDruidï¼‰
  # =========================
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/kyd?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
      username: root
      password: c45540d049692a9c

# =========================
# ğŸš€ RocketMQ é…ç½®
# =========================
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: my-producer-group
    send-message-timeout: 10000
    retry-times-when-send-failed: 3
    retry-next-server: true

# =========================
# ğŸ“¦ ä¸­ç§‘é™¢ä¸“åˆ©æ¥å£é…ç½®
# =========================
yt:
  base-url: http://127.0.0.1:9898/admin/cnipr
  sf1-v1-url: ${yt.base-url}/page
  pi11-url:  ${yt.base-url}/pdfUrl
  pi12-url:  ${yt.base-url}/absUrl
  pi16-url:  ${yt.base-url}/imgUrl

model:
  huoshan:
    modelApiKey: 0ef4713a-70c1-4d45-9226-f6dade8d9026

cas:
  host: "https://cas.example.com/"
  service: "https://kjcgzs.kmmu.edu.cn"

# =========================
# ğŸ· PigX é…ç½®
# =========================
pigx:
  mybatis:
    show-sql: false

# æ–‡ä»¶ä¸Šä¼ é…ç½®
file:
  bucketName: test # ä¸Šæ–‡åˆ›å»ºçš„æ¡¶åç§°
  local:
    enable: true
    base-path: /data/kyd