spring:
  cache:
    type: redis
  redis:
    host: 14.103.149.91
    password: wakeyoga123
    port: 6379
    database: 15
  # 数据库相关配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 2cbef9494050eb99
      url: jdbc:mysql://14.103.149.91:3306/pigxx_boot?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true


# 文件上传配置
file:
  local:
    enable: true
    base-path: /Users/lengleng/Downloads/img

# 验证码配置
aj:
  captcha:
    water-mark: pig4cloud

# 登录报文加密根密钥 ，必须是16位
security:
  encodeKey: pigxpigxpigxpigx

# 配置文件加密根密码
jasypt:
  encryptor:
    password: pigx

# swagger token url 配置
swagger:
  token-url: ${swagger.gateway}/admin/oauth2/token

# jsonflow流程相关配置
flow:
  core:
    orderHttpAddress: http://${pigx-admin:127.0.0.1}:${server.port:9999}/admin
    queryOrder: /order-base/order/flow-inst-id
    updateOrder: /order-base/update-order-info
    startSubFlow: /order-base/start-sub-flow
    restartSubFlow: /order-base/restart-sub-flow
    backParFlow: /order-base/back-par-flow
    listRunByRunJobIds: /handover-node-record/list-run/run-job-ids
    isAllowNoRoleUser: true
    isAllowInitSelf: false
    isRejectAnyNode: true
